#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHeladeria_Sagua.DataClases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HELADERIA_BD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDetalle_Pedido(Detalle_Pedido instance);
    partial void UpdateDetalle_Pedido(Detalle_Pedido instance);
    partial void DeleteDetalle_Pedido(Detalle_Pedido instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertHelado(Helado instance);
    partial void UpdateHelado(Helado instance);
    partial void DeleteHelado(Helado instance);
    partial void InsertHorario(Horario instance);
    partial void UpdateHorario(Horario instance);
    partial void DeleteHorario(Horario instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertRepartidor(Repartidor instance);
    partial void UpdateRepartidor(Repartidor instance);
    partial void DeleteRepartidor(Repartidor instance);
    partial void InsertUbigeo(Ubigeo instance);
    partial void UpdateUbigeo(Ubigeo instance);
    partial void DeleteUbigeo(Ubigeo instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SistemaHeladeria_Sagua.Properties.Settings.Default.HELADERIA_BDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this.GetTable<Detalle_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Helado> Helado
		{
			get
			{
				return this.GetTable<Helado>();
			}
		}
		
		public System.Data.Linq.Table<Horario> Horario
		{
			get
			{
				return this.GetTable<Horario>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedido
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Repartidor> Repartidor
		{
			get
			{
				return this.GetTable<Repartidor>();
			}
		}
		
		public System.Data.Linq.Table<Ubigeo> Ubigeo
		{
			get
			{
				return this.GetTable<Ubigeo>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categ;
		
		private string _nombre;
		
		private string _descripcion;
		
		private char _estado;
		
		private EntitySet<Helado> _Helado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categChanging(int value);
    partial void Onid_categChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    #endregion
		
		public Categoria()
		{
			this._Helado = new EntitySet<Helado>(new Action<Helado>(this.attach_Helado), new Action<Helado>(this.detach_Helado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categ
		{
			get
			{
				return this._id_categ;
			}
			set
			{
				if ((this._id_categ != value))
				{
					this.Onid_categChanging(value);
					this.SendPropertyChanging();
					this._id_categ = value;
					this.SendPropertyChanged("id_categ");
					this.Onid_categChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(70)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Helado", Storage="_Helado", ThisKey="id_categ", OtherKey="id_categ")]
		public EntitySet<Helado> Helado
		{
			get
			{
				return this._Helado;
			}
			set
			{
				this._Helado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Helado(Helado entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Helado(Helado entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_cliente;
		
		private string _dni;
		
		private string _apellido;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _celular;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _fec_nacimiento;
		
		private string _cod_ubigeo;
		
		private EntitySet<Pedido> _Pedido;
		
		private EntityRef<Ubigeo> _Ubigeo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_clienteChanging(string value);
    partial void Oncod_clienteChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onfec_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_nacimientoChanged();
    partial void Oncod_ubigeoChanging(string value);
    partial void Oncod_ubigeoChanged();
    #endregion
		
		public Cliente()
		{
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			this._Ubigeo = default(EntityRef<Ubigeo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(9)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(75)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_nacimiento", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fec_nacimiento
		{
			get
			{
				return this._fec_nacimiento;
			}
			set
			{
				if ((this._fec_nacimiento != value))
				{
					this.Onfec_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fec_nacimiento = value;
					this.SendPropertyChanged("fec_nacimiento");
					this.Onfec_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ubigeo", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string cod_ubigeo
		{
			get
			{
				return this._cod_ubigeo;
			}
			set
			{
				if ((this._cod_ubigeo != value))
				{
					if (this._Ubigeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_ubigeoChanging(value);
					this.SendPropertyChanging();
					this._cod_ubigeo = value;
					this.SendPropertyChanged("cod_ubigeo");
					this.Oncod_ubigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Pedido", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ubigeo_Cliente", Storage="_Ubigeo", ThisKey="cod_ubigeo", OtherKey="cod_ubigeo", IsForeignKey=true)]
		public Ubigeo Ubigeo
		{
			get
			{
				return this._Ubigeo.Entity;
			}
			set
			{
				Ubigeo previousValue = this._Ubigeo.Entity;
				if (((previousValue != value) 
							|| (this._Ubigeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ubigeo.Entity = null;
						previousValue.Cliente.Remove(this);
					}
					this._Ubigeo.Entity = value;
					if ((value != null))
					{
						value.Cliente.Add(this);
						this._cod_ubigeo = value.cod_ubigeo;
					}
					else
					{
						this._cod_ubigeo = default(string);
					}
					this.SendPropertyChanged("Ubigeo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Pedido")]
	public partial class Detalle_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pedido;
		
		private string _cod_pedido;
		
		private string _cod_helado;
		
		private int _cantidad;
		
		private decimal _precioventa;
		
		private EntityRef<Helado> _Helado;
		
		private EntityRef<Pedido> _Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Oncod_pedidoChanging(string value);
    partial void Oncod_pedidoChanged();
    partial void Oncod_heladoChanging(string value);
    partial void Oncod_heladoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnprecioventaChanging(decimal value);
    partial void OnprecioventaChanged();
    #endregion
		
		public Detalle_Pedido()
		{
			this._Helado = default(EntityRef<Helado>);
			this._Pedido = default(EntityRef<Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_pedido", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string cod_pedido
		{
			get
			{
				return this._cod_pedido;
			}
			set
			{
				if ((this._cod_pedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_pedidoChanging(value);
					this.SendPropertyChanging();
					this._cod_pedido = value;
					this.SendPropertyChanged("cod_pedido");
					this.Oncod_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_helado", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string cod_helado
		{
			get
			{
				return this._cod_helado;
			}
			set
			{
				if ((this._cod_helado != value))
				{
					if (this._Helado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_heladoChanging(value);
					this.SendPropertyChanging();
					this._cod_helado = value;
					this.SendPropertyChanged("cod_helado");
					this.Oncod_heladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioventa", DbType="SmallMoney NOT NULL")]
		public decimal precioventa
		{
			get
			{
				return this._precioventa;
			}
			set
			{
				if ((this._precioventa != value))
				{
					this.OnprecioventaChanging(value);
					this.SendPropertyChanging();
					this._precioventa = value;
					this.SendPropertyChanged("precioventa");
					this.OnprecioventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Helado_Detalle_Pedido", Storage="_Helado", ThisKey="cod_helado", OtherKey="cod_helado", IsForeignKey=true)]
		public Helado Helado
		{
			get
			{
				return this._Helado.Entity;
			}
			set
			{
				Helado previousValue = this._Helado.Entity;
				if (((previousValue != value) 
							|| (this._Helado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Helado.Entity = null;
						previousValue.Detalle_Pedido.Remove(this);
					}
					this._Helado.Entity = value;
					if ((value != null))
					{
						value.Detalle_Pedido.Add(this);
						this._cod_helado = value.cod_helado;
					}
					else
					{
						this._cod_helado = default(string);
					}
					this.SendPropertyChanged("Helado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Detalle_Pedido", Storage="_Pedido", ThisKey="cod_pedido", OtherKey="cod_pedido", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Detalle_Pedido.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Detalle_Pedido.Add(this);
						this._cod_pedido = value.cod_pedido;
					}
					else
					{
						this._cod_pedido = default(string);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_empleado;
		
		private string _dni;
		
		private string _apellido;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _celular;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _fec_nacimiento;
		
		private string _cod_ubigeo;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_empleadoChanging(string value);
    partial void Oncod_empleadoChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onfec_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_nacimientoChanged();
    partial void Oncod_ubigeoChanging(string value);
    partial void Oncod_ubigeoChanged();
    #endregion
		
		public Empleado()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_empleado", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_empleado
		{
			get
			{
				return this._cod_empleado;
			}
			set
			{
				if ((this._cod_empleado != value))
				{
					this.Oncod_empleadoChanging(value);
					this.SendPropertyChanging();
					this._cod_empleado = value;
					this.SendPropertyChanged("cod_empleado");
					this.Oncod_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(12)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(75)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_nacimiento", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fec_nacimiento
		{
			get
			{
				return this._fec_nacimiento;
			}
			set
			{
				if ((this._fec_nacimiento != value))
				{
					this.Onfec_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fec_nacimiento = value;
					this.SendPropertyChanged("fec_nacimiento");
					this.Onfec_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ubigeo", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string cod_ubigeo
		{
			get
			{
				return this._cod_ubigeo;
			}
			set
			{
				if ((this._cod_ubigeo != value))
				{
					this.Oncod_ubigeoChanging(value);
					this.SendPropertyChanging();
					this._cod_ubigeo = value;
					this.SendPropertyChanged("cod_ubigeo");
					this.Oncod_ubigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Usuario", ThisKey="cod_empleado", OtherKey="cod_empleado")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Helado")]
	public partial class Helado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_helado;
		
		private int _id_categ;
		
		private string _nombre;
		
		private string _composicion;
		
		private System.Nullable<int> _stock_actual;
		
		private System.Nullable<decimal> _precio;
		
		private EntitySet<Detalle_Pedido> _Detalle_Pedido;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_heladoChanging(string value);
    partial void Oncod_heladoChanged();
    partial void Onid_categChanging(int value);
    partial void Onid_categChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncomposicionChanging(string value);
    partial void OncomposicionChanged();
    partial void Onstock_actualChanging(System.Nullable<int> value);
    partial void Onstock_actualChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    #endregion
		
		public Helado()
		{
			this._Detalle_Pedido = new EntitySet<Detalle_Pedido>(new Action<Detalle_Pedido>(this.attach_Detalle_Pedido), new Action<Detalle_Pedido>(this.detach_Detalle_Pedido));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_helado", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_helado
		{
			get
			{
				return this._cod_helado;
			}
			set
			{
				if ((this._cod_helado != value))
				{
					this.Oncod_heladoChanging(value);
					this.SendPropertyChanging();
					this._cod_helado = value;
					this.SendPropertyChanged("cod_helado");
					this.Oncod_heladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categ", DbType="Int NOT NULL")]
		public int id_categ
		{
			get
			{
				return this._id_categ;
			}
			set
			{
				if ((this._id_categ != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categChanging(value);
					this.SendPropertyChanging();
					this._id_categ = value;
					this.SendPropertyChanged("id_categ");
					this.Onid_categChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_composicion", DbType="VarChar(255)")]
		public string composicion
		{
			get
			{
				return this._composicion;
			}
			set
			{
				if ((this._composicion != value))
				{
					this.OncomposicionChanging(value);
					this.SendPropertyChanging();
					this._composicion = value;
					this.SendPropertyChanged("composicion");
					this.OncomposicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_actual", DbType="Int")]
		public System.Nullable<int> stock_actual
		{
			get
			{
				return this._stock_actual;
			}
			set
			{
				if ((this._stock_actual != value))
				{
					this.Onstock_actualChanging(value);
					this.SendPropertyChanging();
					this._stock_actual = value;
					this.SendPropertyChanged("stock_actual");
					this.Onstock_actualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="SmallMoney")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Helado_Detalle_Pedido", Storage="_Detalle_Pedido", ThisKey="cod_helado", OtherKey="cod_helado")]
		public EntitySet<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this._Detalle_Pedido;
			}
			set
			{
				this._Detalle_Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Helado", Storage="_Categoria", ThisKey="id_categ", OtherKey="id_categ", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Helado.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Helado.Add(this);
						this._id_categ = value.id_categ;
					}
					else
					{
						this._id_categ = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Helado = this;
		}
		
		private void detach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Helado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horario")]
	public partial class Horario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_horario;
		
		private string _descripcion;
		
		private EntitySet<Pedido> _Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_horarioChanging(string value);
    partial void Oncod_horarioChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Horario()
		{
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_horario", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_horario
		{
			get
			{
				return this._cod_horario;
			}
			set
			{
				if ((this._cod_horario != value))
				{
					this.Oncod_horarioChanging(value);
					this.SendPropertyChanging();
					this._cod_horario = value;
					this.SendPropertyChanged("cod_horario");
					this.Oncod_horarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_Pedido", Storage="_Pedido", ThisKey="cod_horario", OtherKey="cod_horario")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Horario = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Horario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_pedido;
		
		private string _cod_cliente;
		
		private int _id_repartidor;
		
		private string _cod_horario;
		
		private System.Nullable<System.DateTime> _fec_pedido;
		
		private System.Nullable<System.DateTime> _fec_expedicion;
		
		private System.Nullable<char> _estado;
		
		private EntitySet<Detalle_Pedido> _Detalle_Pedido;
		
		private EntityRef<Horario> _Horario;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Repartidor> _Repartidor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_pedidoChanging(string value);
    partial void Oncod_pedidoChanged();
    partial void Oncod_clienteChanging(string value);
    partial void Oncod_clienteChanged();
    partial void Onid_repartidorChanging(int value);
    partial void Onid_repartidorChanged();
    partial void Oncod_horarioChanging(string value);
    partial void Oncod_horarioChanged();
    partial void Onfec_pedidoChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_pedidoChanged();
    partial void Onfec_expedicionChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_expedicionChanged();
    partial void OnestadoChanging(System.Nullable<char> value);
    partial void OnestadoChanged();
    #endregion
		
		public Pedido()
		{
			this._Detalle_Pedido = new EntitySet<Detalle_Pedido>(new Action<Detalle_Pedido>(this.attach_Detalle_Pedido), new Action<Detalle_Pedido>(this.detach_Detalle_Pedido));
			this._Horario = default(EntityRef<Horario>);
			this._Cliente = default(EntityRef<Cliente>);
			this._Repartidor = default(EntityRef<Repartidor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_pedido", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_pedido
		{
			get
			{
				return this._cod_pedido;
			}
			set
			{
				if ((this._cod_pedido != value))
				{
					this.Oncod_pedidoChanging(value);
					this.SendPropertyChanging();
					this._cod_pedido = value;
					this.SendPropertyChanged("cod_pedido");
					this.Oncod_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_repartidor", DbType="Int NOT NULL")]
		public int id_repartidor
		{
			get
			{
				return this._id_repartidor;
			}
			set
			{
				if ((this._id_repartidor != value))
				{
					if (this._Repartidor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_repartidorChanging(value);
					this.SendPropertyChanging();
					this._id_repartidor = value;
					this.SendPropertyChanged("id_repartidor");
					this.Onid_repartidorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_horario", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string cod_horario
		{
			get
			{
				return this._cod_horario;
			}
			set
			{
				if ((this._cod_horario != value))
				{
					if (this._Horario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_horarioChanging(value);
					this.SendPropertyChanging();
					this._cod_horario = value;
					this.SendPropertyChanged("cod_horario");
					this.Oncod_horarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_pedido", DbType="DateTime")]
		public System.Nullable<System.DateTime> fec_pedido
		{
			get
			{
				return this._fec_pedido;
			}
			set
			{
				if ((this._fec_pedido != value))
				{
					this.Onfec_pedidoChanging(value);
					this.SendPropertyChanging();
					this._fec_pedido = value;
					this.SendPropertyChanged("fec_pedido");
					this.Onfec_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_expedicion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fec_expedicion
		{
			get
			{
				return this._fec_expedicion;
			}
			set
			{
				if ((this._fec_expedicion != value))
				{
					this.Onfec_expedicionChanging(value);
					this.SendPropertyChanging();
					this._fec_expedicion = value;
					this.SendPropertyChanged("fec_expedicion");
					this.Onfec_expedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1)")]
		public System.Nullable<char> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Detalle_Pedido", Storage="_Detalle_Pedido", ThisKey="cod_pedido", OtherKey="cod_pedido")]
		public EntitySet<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this._Detalle_Pedido;
			}
			set
			{
				this._Detalle_Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_Pedido", Storage="_Horario", ThisKey="cod_horario", OtherKey="cod_horario", IsForeignKey=true)]
		public Horario Horario
		{
			get
			{
				return this._Horario.Entity;
			}
			set
			{
				Horario previousValue = this._Horario.Entity;
				if (((previousValue != value) 
							|| (this._Horario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Horario.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Horario.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._cod_horario = value.cod_horario;
					}
					else
					{
						this._cod_horario = default(string);
					}
					this.SendPropertyChanged("Horario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Repartidor_Pedido", Storage="_Repartidor", ThisKey="id_repartidor", OtherKey="id_repartidor", IsForeignKey=true)]
		public Repartidor Repartidor
		{
			get
			{
				return this._Repartidor.Entity;
			}
			set
			{
				Repartidor previousValue = this._Repartidor.Entity;
				if (((previousValue != value) 
							|| (this._Repartidor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Repartidor.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Repartidor.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._id_repartidor = value.id_repartidor;
					}
					else
					{
						this._id_repartidor = default(int);
					}
					this.SendPropertyChanged("Repartidor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Repartidor")]
	public partial class Repartidor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_repartidor;
		
		private string _apellido;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _cod_ubigeo;
		
		private EntitySet<Pedido> _Pedido;
		
		private EntityRef<Ubigeo> _Ubigeo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_repartidorChanging(int value);
    partial void Onid_repartidorChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Oncod_ubigeoChanging(string value);
    partial void Oncod_ubigeoChanged();
    #endregion
		
		public Repartidor()
		{
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			this._Ubigeo = default(EntityRef<Ubigeo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_repartidor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_repartidor
		{
			get
			{
				return this._id_repartidor;
			}
			set
			{
				if ((this._id_repartidor != value))
				{
					this.Onid_repartidorChanging(value);
					this.SendPropertyChanging();
					this._id_repartidor = value;
					this.SendPropertyChanged("id_repartidor");
					this.Onid_repartidorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ubigeo", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string cod_ubigeo
		{
			get
			{
				return this._cod_ubigeo;
			}
			set
			{
				if ((this._cod_ubigeo != value))
				{
					if (this._Ubigeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_ubigeoChanging(value);
					this.SendPropertyChanging();
					this._cod_ubigeo = value;
					this.SendPropertyChanged("cod_ubigeo");
					this.Oncod_ubigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Repartidor_Pedido", Storage="_Pedido", ThisKey="id_repartidor", OtherKey="id_repartidor")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ubigeo_Repartidor", Storage="_Ubigeo", ThisKey="cod_ubigeo", OtherKey="cod_ubigeo", IsForeignKey=true)]
		public Ubigeo Ubigeo
		{
			get
			{
				return this._Ubigeo.Entity;
			}
			set
			{
				Ubigeo previousValue = this._Ubigeo.Entity;
				if (((previousValue != value) 
							|| (this._Ubigeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ubigeo.Entity = null;
						previousValue.Repartidor.Remove(this);
					}
					this._Ubigeo.Entity = value;
					if ((value != null))
					{
						value.Repartidor.Add(this);
						this._cod_ubigeo = value.cod_ubigeo;
					}
					else
					{
						this._cod_ubigeo = default(string);
					}
					this.SendPropertyChanged("Ubigeo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Repartidor = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Repartidor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ubigeo")]
	public partial class Ubigeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_ubigeo;
		
		private string _descripcion;
		
		private string _cod_ubigeo_sup;
		
		private EntitySet<Cliente> _Cliente;
		
		private EntitySet<Repartidor> _Repartidor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_ubigeoChanging(string value);
    partial void Oncod_ubigeoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oncod_ubigeo_supChanging(string value);
    partial void Oncod_ubigeo_supChanged();
    #endregion
		
		public Ubigeo()
		{
			this._Cliente = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Cliente), new Action<Cliente>(this.detach_Cliente));
			this._Repartidor = new EntitySet<Repartidor>(new Action<Repartidor>(this.attach_Repartidor), new Action<Repartidor>(this.detach_Repartidor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ubigeo", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_ubigeo
		{
			get
			{
				return this._cod_ubigeo;
			}
			set
			{
				if ((this._cod_ubigeo != value))
				{
					this.Oncod_ubigeoChanging(value);
					this.SendPropertyChanging();
					this._cod_ubigeo = value;
					this.SendPropertyChanged("cod_ubigeo");
					this.Oncod_ubigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(70)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ubigeo_sup", DbType="Char(6)")]
		public string cod_ubigeo_sup
		{
			get
			{
				return this._cod_ubigeo_sup;
			}
			set
			{
				if ((this._cod_ubigeo_sup != value))
				{
					this.Oncod_ubigeo_supChanging(value);
					this.SendPropertyChanging();
					this._cod_ubigeo_sup = value;
					this.SendPropertyChanged("cod_ubigeo_sup");
					this.Oncod_ubigeo_supChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ubigeo_Cliente", Storage="_Cliente", ThisKey="cod_ubigeo", OtherKey="cod_ubigeo")]
		public EntitySet<Cliente> Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				this._Cliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ubigeo_Repartidor", Storage="_Repartidor", ThisKey="cod_ubigeo", OtherKey="cod_ubigeo")]
		public EntitySet<Repartidor> Repartidor
		{
			get
			{
				return this._Repartidor;
			}
			set
			{
				this._Repartidor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Ubigeo = this;
		}
		
		private void detach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Ubigeo = null;
		}
		
		private void attach_Repartidor(Repartidor entity)
		{
			this.SendPropertyChanging();
			entity.Ubigeo = this;
		}
		
		private void detach_Repartidor(Repartidor entity)
		{
			this.SendPropertyChanging();
			entity.Ubigeo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _cod_empleado;
		
		private string _nombre;
		
		private string _clave;
		
		private string _nivel;
		
		private char _estado;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Oncod_empleadoChanging(string value);
    partial void Oncod_empleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnnivelChanging(string value);
    partial void OnnivelChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    #endregion
		
		public Usuario()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_empleado", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string cod_empleado
		{
			get
			{
				return this._cod_empleado;
			}
			set
			{
				if ((this._cod_empleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_empleadoChanging(value);
					this.SendPropertyChanging();
					this._cod_empleado = value;
					this.SendPropertyChanged("cod_empleado");
					this.Oncod_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this.OnnivelChanging(value);
					this.SendPropertyChanging();
					this._nivel = value;
					this.SendPropertyChanged("nivel");
					this.OnnivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Empleado", ThisKey="cod_empleado", OtherKey="cod_empleado", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._cod_empleado = value.cod_empleado;
					}
					else
					{
						this._cod_empleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
